/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finance.ui;

import finance.Investment;
import finance.LoanPayment;
import finance.Report;
import finance.TVMEngine;
import finance.enums.CompoundingOption;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import finance.ui.SwingValidator;

/**
 *
 * @author koluongMBP
 * @version 161017
 */
public class FinanceAnalyzerForm extends javax.swing.JFrame {

    private CompoundingOption cOption;
    private TVMEngine calculator;
    private Report report;
    private SwingValidator valid;
    private Boolean terminate = false;

    /**
     * Creates new form FinanceAnalyzerForm
     */
    public FinanceAnalyzerForm() {
        initComponents();
        cOption = CompoundingOption.ANNUAL;
        calculator = new LoanPayment();
        report = null;
        valid = new SwingValidator();
        optCheck.setSelected(false);
        optText.setEnabled(false);
        optText.setText("0");
        summaryReportButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeSelect = new javax.swing.ButtonGroup();
        summaryReportWindow = new javax.swing.JDialog();
        guiTitle = new javax.swing.JLabel();
        loanRadioButton = new javax.swing.JRadioButton();
        investmentRadioButton = new javax.swing.JRadioButton();
        reqLabel = new javax.swing.JLabel();
        loanAmountLabel = new javax.swing.JLabel();
        aprLabel = new javax.swing.JLabel();
        compoundingLabel = new javax.swing.JLabel();
        durationLabel = new javax.swing.JLabel();
        finalLabel = new javax.swing.JLabel();
        optCheck = new javax.swing.JCheckBox();
        calculateButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        summaryReportButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        reqText = new javax.swing.JTextField();
        optText = new javax.swing.JTextField();
        loanAmountText = new javax.swing.JTextField();
        aprText = new javax.swing.JTextField();
        durationText = new javax.swing.JTextField();
        finalText = new javax.swing.JTextField();
        compoundingBox = new javax.swing.JComboBox<>();

        summaryReportWindow.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        summaryReportWindow.setTitle("Summary Report");

        javax.swing.GroupLayout summaryReportWindowLayout = new javax.swing.GroupLayout(summaryReportWindow.getContentPane());
        summaryReportWindow.getContentPane().setLayout(summaryReportWindowLayout);
        summaryReportWindowLayout.setHorizontalGroup(
            summaryReportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        summaryReportWindowLayout.setVerticalGroup(
            summaryReportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Financial Calculator");

        guiTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        guiTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guiTitle.setText("Loan Payment Calculator");

        modeSelect.add(loanRadioButton);
        loanRadioButton.setSelected(true);
        loanRadioButton.setText("Loan Payment");
        loanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanRadioButtonActionPerformed(evt);
            }
        });

        modeSelect.add(investmentRadioButton);
        investmentRadioButton.setText("Investment");
        investmentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                investmentRadioButtonActionPerformed(evt);
            }
        });

        reqLabel.setText("Purchase Amount");

        loanAmountLabel.setText("Loan Amount");

        aprLabel.setText("APR%");

        compoundingLabel.setText("Compounding");

        durationLabel.setText("Loan Duration (years)");

        finalLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        finalLabel.setText("Monthly Payment");

        optCheck.setText("Down Payment");
        optCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optCheckActionPerformed(evt);
            }
        });

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        summaryReportButton.setText("Summary Report");
        summaryReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryReportButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        reqText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqTextActionPerformed(evt);
            }
        });

        optText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optTextActionPerformed(evt);
            }
        });

        loanAmountText.setBackground(java.awt.Color.lightGray);
        loanAmountText.setText(" ");
        loanAmountText.setFocusable(false);
        loanAmountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanAmountTextActionPerformed(evt);
            }
        });

        aprText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aprTextActionPerformed(evt);
            }
        });

        durationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationTextActionPerformed(evt);
            }
        });

        finalText.setBackground(java.awt.Color.lightGray);
        finalText.setText(" ");
        finalText.setFocusable(false);

        compoundingBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Annual", "Semiannual", "Quarterly", "Monthly", "Weekly" }));
        compoundingBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compoundingBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loanAmountLabel)
                            .addComponent(aprLabel))
                        .addGap(118, 353, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(reqLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clearButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exitButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(optCheck)
                                    .addComponent(finalLabel)
                                    .addComponent(durationLabel)
                                    .addComponent(compoundingLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(durationText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(finalText, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(optText)
                                    .addComponent(reqText)
                                    .addComponent(loanAmountText)
                                    .addComponent(aprText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(compoundingBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(calculateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(summaryReportButton)))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(loanRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(investmentRadioButton)
                        .addGap(112, 112, 112))))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(guiTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loanRadioButton)
                    .addComponent(investmentRadioButton))
                .addGap(18, 18, 18)
                .addComponent(guiTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reqLabel)
                    .addComponent(reqText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optCheck)
                    .addComponent(optText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loanAmountLabel)
                    .addComponent(loanAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aprLabel)
                    .addComponent(aprText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compoundingLabel)
                    .addComponent(compoundingBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(durationLabel)
                    .addComponent(durationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finalLabel)
                    .addComponent(finalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateButton)
                    .addComponent(summaryReportButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton)
                    .addComponent(exitButton))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void reqTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reqTextActionPerformed

    private void durationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationTextActionPerformed

    private void investmentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_investmentRadioButtonActionPerformed
        guiTitle.setText("Investment Value Calculator");
        reqLabel.setText("Monthly Investment");
        optCheck.setText("Initial Investment");
        optCheck.setSelected(false);
        optText.setEnabled(true);
        optText.setText("0");
        compoundingBox.setSelectedIndex(0);
        durationLabel.setText("Investment Period (years)");
        loanAmountText.setText("");
        loanAmountLabel.setVisible(false);
        loanAmountText.setEnabled(false);
        cOption = CompoundingOption.ANNUAL;
        finalLabel.setText("Future Value");
        optCheck.setSelected(false);
        optText.setEnabled(false);
        optText.setText("0");
        summaryReportButton.setEnabled(false);
        clear();
    }//GEN-LAST:event_investmentRadioButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clear();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void loanAmountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanAmountTextActionPerformed

    }//GEN-LAST:event_loanAmountTextActionPerformed

    private void loanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanRadioButtonActionPerformed
        guiTitle.setText("Loan Payment Calculator");
        reqLabel.setText("Purchase Amount");
        optCheck.setSelected(false);
        optCheck.setText("Down Payment");
        optText.setText("0");
        optText.setEnabled(true);
        compoundingBox.setSelectedIndex(0);
        loanAmountLabel.setVisible(true);
        loanAmountText.setEnabled(true);
        cOption = CompoundingOption.ANNUAL;
        durationLabel.setText("Loan Duration (years)");
        finalLabel.setText("Monthly Payment");
        optCheck.setSelected(false);
        optText.setEnabled(false);
        optText.setText("0");
        summaryReportButton.setEnabled(false);
        clear();
    }//GEN-LAST:event_loanRadioButtonActionPerformed

    private void optTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optTextActionPerformed

    }//GEN-LAST:event_optTextActionPerformed

    private void optCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optCheckActionPerformed
        if (optCheck.isSelected()) {
            optText.setEnabled(true);
            optText.setText("");
        } else {
            optText.setEnabled(false);
            optText.setText("0");
        }
    }//GEN-LAST:event_optCheckActionPerformed

    private void compoundingBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compoundingBoxActionPerformed
        String option = (String) compoundingBox.getSelectedItem();
        if (loanRadioButton.isSelected()) {
            finalLabel.setText(option + " Payment");
        } else {
            reqLabel.setText(option + " Investment");
        }

        cOption = CompoundingOption.ANNUAL;
        if (option.equals("Semiannual")) {
            cOption = CompoundingOption.SEMIANNUAL;
        } else if (option.equals("Quarterly")) {
            cOption = CompoundingOption.QUARTERLY;
        } else if (option.equals("Monthly")) {
            cOption = CompoundingOption.MONTHLY;
        } else if (option.equals("Weekly")) {
            cOption = CompoundingOption.WEEKLY;
        }
    }//GEN-LAST:event_compoundingBoxActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed

        if (numberValid()) {

            double apr = Double.parseDouble(aprText.getText());
            double years = Double.parseDouble(durationText.getText());
            double reqCF = Double.parseDouble(reqText.getText());
            double optCF = Double.parseDouble(optText.getText());

            if (loanRadioButton.isSelected()) {
                //Loan Mode

                double loan = reqCF - optCF;

                while (loan < 0) {
                    JOptionPane.showMessageDialog(null, "Loan Amount must be greater or equal to zero.", "Invalid Entry", 0);
                    clearFinal();
                    return;
                }

                loanAmountText.setText(calculator.toCurrency(loan));
                LoanPayment lp = new LoanPayment(reqCF, optCF, apr, cOption, years);
                calculator = lp;
                report = lp;
            } else {
                //Investment Mode
                Investment invest = new Investment(optCF, reqCF, apr, cOption, years);
                calculator = invest;
                report = invest;
            }
            finalText.setText(calculator.getValue());
            summaryReportButton.setEnabled(true);
        }
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void summaryReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryReportButtonActionPerformed

        JOptionPane.showMessageDialog(null, report.print(), "Summary Report", 1);
    }//GEN-LAST:event_summaryReportButtonActionPerformed

    private void aprTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aprTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aprTextActionPerformed

    private void clear() {
        if (optCheck.isSelected()) {
            optText.setText("");
        }
        reqText.setText("");
        aprText.setText("");
        durationText.setText("");
        finalText.setText("");
        loanAmountText.setText("");
        summaryReportButton.setEnabled(false);
    }

    private void clearFinal() {
        finalText.setText("");
        loanAmountText.setText("");
    }

    private boolean numberValid() {
        
        return valid.isPresent(reqText, reqLabel.getText()) &&
               valid.isDoubleGreaterThanZero(reqText, reqLabel.getText()) &&
               valid.isPresent(aprText, aprLabel.getText()) &&
                valid.isDouble(aprText, aprLabel.getText()) &&
               valid.isDoublePositive(aprText, aprLabel.getText()) &&
                valid.isPresent(durationText, durationLabel.getText()) &&
                valid.isInteger(durationText, durationLabel.getText()) &&
                valid.isDoublePositive(durationText, durationLabel.getText());

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinanceAnalyzerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinanceAnalyzerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinanceAnalyzerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinanceAnalyzerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                FinanceAnalyzerForm frame = new FinanceAnalyzerForm();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aprLabel;
    private javax.swing.JTextField aprText;
    private javax.swing.JButton calculateButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox<String> compoundingBox;
    private javax.swing.JLabel compoundingLabel;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JTextField durationText;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel finalLabel;
    private javax.swing.JTextField finalText;
    private javax.swing.JLabel guiTitle;
    private javax.swing.JRadioButton investmentRadioButton;
    private javax.swing.JLabel loanAmountLabel;
    private javax.swing.JTextField loanAmountText;
    private javax.swing.JRadioButton loanRadioButton;
    private javax.swing.ButtonGroup modeSelect;
    private javax.swing.JCheckBox optCheck;
    private javax.swing.JTextField optText;
    private javax.swing.JLabel reqLabel;
    private javax.swing.JTextField reqText;
    private javax.swing.JButton summaryReportButton;
    private javax.swing.JDialog summaryReportWindow;
    // End of variables declaration//GEN-END:variables
}
